

POST http://127.0.0.1:3434/recipes
content-type: application/json

{
    "search_term": "",
    "keywords": []
}

### Single recipe request
POST http://35.228.26.195:8000/recipes/d28e8ccf-15af-41fd-aa4b-c6c3fdf6b188 
content-type: application/json

{
    "keywords": []
}


### Single recipe request
GET http://35.228.26.195:8000/ingredients/8710437001700


### Gets all similar keywords matching typed 
GET http://127.0.0.1:3434/keywords?query=so

### Returns all keywords
GET http://127.0.0.1:3434/all_keywords
